INSERT INTO 
	Unit (BaseUnit_BasicAuthority, BaseUnit_Description, CatalogName, CatalogSymbol_isExplicit, CatalogSymbol_text, ConversionToBaseUnit_Factor,
	ConversionToBaseUnit_Formula_A, ConversionToBaseUnit_Formula_B, ConversionToBaseUnit_Formula_C, ConversionToBaseUnit_Formula_D,
	ConversionToBaseUnit_Fraction_Denominator, ConversionToBaseUnit_Fraction_Numerator, ConversionToBaseUnit_baseUnit,
	Deprecated, DimensionalClass, Name, Annotation, Id)
SELECT 
	BaseUnit_BasicAuthority, BaseUnit_Description, CatalogName, CatalogSymbol_isExplicit, CatalogSymbol_text, ConversionToBaseUnit_Factor,
	ConversionToBaseUnit_Formula_A, ConversionToBaseUnit_Formula_B, ConversionToBaseUnit_Formula_C, ConversionToBaseUnit_Formula_D,
	ConversionToBaseUnit_Fraction_Denominator, ConversionToBaseUnit_Fraction_Numerator, ConversionToBaseUnit_baseUnit,
	Deprecated,DimensionalClass, Name, Annotation, Id
FROM UnitsOfMeasure