INSERT INTO quantityType (Name) values ('absorbed dose');
INSERT INTO quantityType (Name) values ('acceleration linear');
INSERT INTO quantityType (Name) values ('activity (of radioactivity)');
INSERT INTO quantityType (Name) values ('amount of substance');
INSERT INTO quantityType (Name) values ('angle per length');
INSERT INTO quantityType (Name) values ('angle per volume');
INSERT INTO quantityType (Name) values ('angular acceleration');
INSERT INTO quantityType (Name) values ('angular velocity');
INSERT INTO quantityType (Name) values ('area');
INSERT INTO quantityType (Name) values ('area per area');
INSERT INTO quantityType (Name) values ('area per volume');
INSERT INTO quantityType (Name) values ('attenuation');
INSERT INTO quantityType (Name) values ('attenuation per length');
INSERT INTO quantityType (Name) values ('bulk compressibility');
INSERT INTO quantityType (Name) values ('capacitance');
INSERT INTO quantityType (Name) values ('Cartesian coordinates');
INSERT INTO quantityType (Name) values ('charge density');
INSERT INTO quantityType (Name) values ('concentration of B');
INSERT INTO quantityType (Name) values ('conductivity');
INSERT INTO quantityType (Name) values ('cross section absorption');
INSERT INTO quantityType (Name) values ('current density');
INSERT INTO quantityType (Name) values ('Darcy flow coefficient');
INSERT INTO quantityType (Name) values ('data transmission speed');
INSERT INTO quantityType (Name) values ('delta temperature');
INSERT INTO quantityType (Name) values ('density');
INSERT INTO quantityType (Name) values ('density of heat flow rate');
INSERT INTO quantityType (Name) values ('depth');
INSERT INTO quantityType (Name) values ('diameter');
INSERT INTO quantityType (Name) values ('digital storage');
INSERT INTO quantityType (Name) values ('dimensionless');
INSERT INTO quantityType (Name) values ('distance');
INSERT INTO quantityType (Name) values ('dose equivalent');
INSERT INTO quantityType (Name) values ('dose equivalent rate');
INSERT INTO quantityType (Name) values ('dynamic viscosity');
INSERT INTO quantityType (Name) values ('electric capacity');
INSERT INTO quantityType (Name) values ('electric conductance');
INSERT INTO quantityType (Name) values ('electric current');
INSERT INTO quantityType (Name) values ('electric dipole moment');
INSERT INTO quantityType (Name) values ('electric field strength');
INSERT INTO quantityType (Name) values ('electric polarization');
INSERT INTO quantityType (Name) values ('electric potential');
INSERT INTO quantityType (Name) values ('electrical resistivity');
INSERT INTO quantityType (Name) values ('electrochemical equivalent');
INSERT INTO quantityType (Name) values ('electromagnetic energy density');
INSERT INTO quantityType (Name) values ('electromagnetic moment');
INSERT INTO quantityType (Name) values ('energy');
INSERT INTO quantityType (Name) values ('energy fluence rate');
INSERT INTO quantityType (Name) values ('energy length per area');
INSERT INTO quantityType (Name) values ('energy length per time area temperature');
INSERT INTO quantityType (Name) values ('energy per area');
INSERT INTO quantityType (Name) values ('energy per length');
INSERT INTO quantityType (Name) values ('equivalent per mass');
INSERT INTO quantityType (Name) values ('equivalent per volume');
INSERT INTO quantityType (Name) values ('exposure (radioactivity)');
INSERT INTO quantityType (Name) values ('force');
INSERT INTO quantityType (Name) values ('force area');
INSERT INTO quantityType (Name) values ('force length per length');
INSERT INTO quantityType (Name) values ('force per area');
INSERT INTO quantityType (Name) values ('force per force');
INSERT INTO quantityType (Name) values ('force per length');
INSERT INTO quantityType (Name) values ('force per volume');
INSERT INTO quantityType (Name) values ('frequency');
INSERT INTO quantityType (Name) values ('frequency interval');
INSERT INTO quantityType (Name) values ('gamma ray API unit');
INSERT INTO quantityType (Name) values ('heat capacity');
INSERT INTO quantityType (Name) values ('heat flow rate');
INSERT INTO quantityType (Name) values ('heat transfer coefficient');
INSERT INTO quantityType (Name) values ('illuminance');
INSERT INTO quantityType (Name) values ('isothermal compressibility');
INSERT INTO quantityType (Name) values ('kinematic viscosity');
INSERT INTO quantityType (Name) values ('length');
INSERT INTO quantityType (Name) values ('length of path');
INSERT INTO quantityType (Name) values ('length per length');
INSERT INTO quantityType (Name) values ('length per temperature');
INSERT INTO quantityType (Name) values ('length per volume');
INSERT INTO quantityType (Name) values ('level of power intensity');
INSERT INTO quantityType (Name) values ('light exposure');
INSERT INTO quantityType (Name) values ('linear density');
INSERT INTO quantityType (Name) values ('linear electric current density');
INSERT INTO quantityType (Name) values ('linear strain');
INSERT INTO quantityType (Name) values ('linear thermal expansion');
INSERT INTO quantityType (Name) values ('luminance');
INSERT INTO quantityType (Name) values ('luminous efficacy');
INSERT INTO quantityType (Name) values ('luminous exitance');
INSERT INTO quantityType (Name) values ('luminous flux');
INSERT INTO quantityType (Name) values ('luminous intensity');
INSERT INTO quantityType (Name) values ('magnetic dipole moment');
INSERT INTO quantityType (Name) values ('magnetic flux');
INSERT INTO quantityType (Name) values ('magnetic induction');
INSERT INTO quantityType (Name) values ('magnetic permeability');
INSERT INTO quantityType (Name) values ('magnetic vector potential');
INSERT INTO quantityType (Name) values ('mass');
INSERT INTO quantityType (Name) values ('mass attenuation coefficient');
INSERT INTO quantityType (Name) values ('mass concentration');
INSERT INTO quantityType (Name) values ('mass flow rate');
INSERT INTO quantityType (Name) values ('mass length');
INSERT INTO quantityType (Name) values ('mass per energy');
INSERT INTO quantityType (Name) values ('mass per length');
INSERT INTO quantityType (Name) values ('mass per time per area');
INSERT INTO quantityType (Name) values ('mass per time per length');
INSERT INTO quantityType (Name) values ('mass per volume per length');
INSERT INTO quantityType (Name) values ('mean free path');
INSERT INTO quantityType (Name) values ('mobility');
INSERT INTO quantityType (Name) values ('molar heat capacity');
INSERT INTO quantityType (Name) values ('molar thermodynamic energy');
INSERT INTO quantityType (Name) values ('molar volume');
INSERT INTO quantityType (Name) values ('mole per area');
INSERT INTO quantityType (Name) values ('mole per time');
INSERT INTO quantityType (Name) values ('mole per time per area');
INSERT INTO quantityType (Name) values ('moment of force');
INSERT INTO quantityType (Name) values ('moment of inertia');
INSERT INTO quantityType (Name) values ('momentum');
INSERT INTO quantityType (Name) values ('neutron API unit');
INSERT INTO quantityType (Name) values ('nonDarcy flow coefficient');
INSERT INTO quantityType (Name) values ('normal stress');
INSERT INTO quantityType (Name) values ('operations per time');
INSERT INTO quantityType (Name) values ('parachor');
INSERT INTO quantityType (Name) values ('per area');
INSERT INTO quantityType (Name) values ('per electric potential');
INSERT INTO quantityType (Name) values ('per force');
INSERT INTO quantityType (Name) values ('per length');
INSERT INTO quantityType (Name) values ('per mass');
INSERT INTO quantityType (Name) values ('per time');
INSERT INTO quantityType (Name) values ('per volume');
INSERT INTO quantityType (Name) values ('permeability length');
INSERT INTO quantityType (Name) values ('permeability rock');
INSERT INTO quantityType (Name) values ('permittivity');
INSERT INTO quantityType (Name) values ('pH');
INSERT INTO quantityType (Name) values ('plane angle');
INSERT INTO quantityType (Name) values ('poisson ratio');
INSERT INTO quantityType (Name) values ('potential difference per per power drop');
INSERT INTO quantityType (Name) values ('power');
INSERT INTO quantityType (Name) values ('power per volume');
INSERT INTO quantityType (Name) values ('pressure per time');
INSERT INTO quantityType (Name) values ('pressure squared');
INSERT INTO quantityType (Name) values ('pressure squared per (dynamic viscosity)');
INSERT INTO quantityType (Name) values ('pressure time per volume');
INSERT INTO quantityType (Name) values ('productivity index');
INSERT INTO quantityType (Name) values ('quantity of light');
INSERT INTO quantityType (Name) values ('radiance');
INSERT INTO quantityType (Name) values ('radiant energy density');
INSERT INTO quantityType (Name) values ('radiant intensity');
INSERT INTO quantityType (Name) values ('relative power');
INSERT INTO quantityType (Name) values ('relative time');
INSERT INTO quantityType (Name) values ('reluctance');
INSERT INTO quantityType (Name) values ('resistance');
INSERT INTO quantityType (Name) values ('resistivity per length');
INSERT INTO quantityType (Name) values ('rotational frequency');
INSERT INTO quantityType (Name) values ('scale');
INSERT INTO quantityType (Name) values ('second moment of area');
INSERT INTO quantityType (Name) values ('self inductance');
INSERT INTO quantityType (Name) values ('solid angle');
INSERT INTO quantityType (Name) values ('specific activity (of radioactivity)');
INSERT INTO quantityType (Name) values ('specific energy');
INSERT INTO quantityType (Name) values ('specific heat capacity');
INSERT INTO quantityType (Name) values ('specific productivity index');
INSERT INTO quantityType (Name) values ('specific volume');
INSERT INTO quantityType (Name) values ('stadard volume per volume');
INSERT INTO quantityType (Name) values ('standard volume');
INSERT INTO quantityType (Name) values ('standard volume  per area');
INSERT INTO quantityType (Name) values ('standard volume per area');
INSERT INTO quantityType (Name) values ('standard volume per time');
INSERT INTO quantityType (Name) values ('standard volume per volume');
INSERT INTO quantityType (Name) values ('surface density');
INSERT INTO quantityType (Name) values ('temperature per length');
INSERT INTO quantityType (Name) values ('temperature per time');
INSERT INTO quantityType (Name) values ('thermal conductance');
INSERT INTO quantityType (Name) values ('thermal conductivity');
INSERT INTO quantityType (Name) values ('thermal insulance');
INSERT INTO quantityType (Name) values ('thermal resistance');
INSERT INTO quantityType (Name) values ('thermodynamic temperature');
INSERT INTO quantityType (Name) values ('time');
INSERT INTO quantityType (Name) values ('time per length');
INSERT INTO quantityType (Name) values ('time per volume');
INSERT INTO quantityType (Name) values ('unit productivity index');
INSERT INTO quantityType (Name) values ('velocity');
INSERT INTO quantityType (Name) values ('volume');
INSERT INTO quantityType (Name) values ('volume flow rate');
INSERT INTO quantityType (Name) values ('volume length per time');
INSERT INTO quantityType (Name) values ('volume per area');
INSERT INTO quantityType (Name) values ('volume per length');
INSERT INTO quantityType (Name) values ('volume per standard volume');
INSERT INTO quantityType (Name) values ('volume per time per area');
INSERT INTO quantityType (Name) values ('volume per time per length');
INSERT INTO quantityType (Name) values ('volume per time per time');
INSERT INTO quantityType (Name) values ('volume per time per volume');
INSERT INTO quantityType (Name) values ('volume per volume');
INSERT INTO quantityType (Name) values ('volumetric heat transfer coefficient');
INSERT INTO quantityType (Name) values ('volumetric thermal expansion');
INSERT INTO quantityType (Name) values ('volumic concentration');
INSERT INTO quantityType (Name) values ('wavelength');
